codecov:
  require_ci_to_pass: false

ignore:
  - "sandbox/**/*"
  - "tests/**/*"

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
