<?php

declare(strict_types=1);

namespace Atlasphp\Atlas\Persistence\Models;

use Atlasphp\Atlas\Database\Factories\ConversationMessageAssetFactory;
use Atlasphp\Atlas\Persistence\Concerns\HasAtlasTable;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * Class MessageAsset
 *
 * Join model linking messages to assets. A message can have multiple attachments and an asset
 * can be referenced by multiple messages. No direction column — the parent message's role
 * determines whether the attachment was sent by the user or generated by the agent.
 *
 * @property int $id
 * @property int $message_id
 * @property int $asset_id
 * @property array<string, mixed>|null $metadata
 * @property Carbon $created_at
 */
class ConversationMessageAsset extends Model
{
    /** @use HasFactory<Factory<static>> */
    use HasAtlasTable, HasFactory;

    protected static function newFactory(): ConversationMessageAssetFactory
    {
        return ConversationMessageAssetFactory::new();
    }

    public const UPDATED_AT = null;

    protected $table = 'conversation_message_assets';

    protected $fillable = [
        'message_id',
        'asset_id',
        'metadata',
    ];

    protected function casts(): array
    {
        return [
            'metadata' => 'array',
        ];
    }

    // ─── Relationships ──────────────────────────────────────────

    /** @return BelongsTo<ConversationMessage, $this> */
    public function message(): BelongsTo
    {
        /** @var class-string<ConversationMessage> $model */
        $model = config('atlas.persistence.models.conversation_message', ConversationMessage::class);

        return $this->belongsTo($model);
    }

    /** @return BelongsTo<Asset, $this> */
    public function asset(): BelongsTo
    {
        /** @var class-string<Asset> $model */
        $model = config('atlas.persistence.models.asset', Asset::class);

        return $this->belongsTo($model);
    }
}
