<?php

declare(strict_types=1);

namespace Atlasphp\Atlas\Streaming\Events;

use Atlasphp\Atlas\Streaming\StreamEvent;

/**
 * Event emitted when an artifact is received from a tool call.
 *
 * Contains artifact data generated by a tool during execution.
 */
final readonly class ArtifactEvent extends StreamEvent
{
    /**
     * @param  string  $id  Unique identifier for this event.
     * @param  int  $timestamp  Unix timestamp when the event was created.
     * @param  array<string, mixed>  $artifact  The artifact data.
     * @param  string  $toolCallId  The tool call that generated this artifact.
     * @param  string  $toolName  The name of the tool.
     * @param  string  $messageId  The message this artifact belongs to.
     */
    public function __construct(
        string $id,
        int $timestamp,
        public array $artifact,
        public string $toolCallId,
        public string $toolName,
        public string $messageId,
    ) {
        parent::__construct($id, $timestamp);
    }

    public function type(): string
    {
        return 'artifact';
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'type' => $this->type(),
            'timestamp' => $this->timestamp,
            'artifact' => $this->artifact,
            'tool_call_id' => $this->toolCallId,
            'tool_name' => $this->toolName,
            'message_id' => $this->messageId,
        ];
    }
}
